port: 9000
name: traffic-proxy dev-mode
servers:
  - name: backend service1
    mode: proxy
    source: "http://0.0.0.0:13000"
    backend: "http://0.0.0.0:3000"
    storage: "inmemory:///dev-test/bk-service0"
  - name: backend service1
    mode: proxy
    source: "http://0.0.0.0:13001"
    backend: "http://0.0.0.0:3001"
    storage: "inmemory:///dev-test/bk-service1"
  - name: backend service2
    mode: proxy
    source: "http://0.0.0.0:13002"
    backend: "http://0.0.0.0:3002"
    storage: "inmemory:///dev-test/bk-service2"
  - name: frontend service
    mode: proxy
    source: "http://0.0.0.0:14000"
    backend: "http://0.0.0.0:4000"
    storage: "inmemory:///dev-test/fe-service0"
  - name: mysql service
    mode: proxy
    source: "mysql://0.0.0.0:13306"
    backend: "mysql://0.0.0.0:3306"
    storage: "inmemory:///dev-test/mysql"
  - name: pgsql service
    mode: proxy
    source: "pgsql://0.0.0.0:15432"
    backend: "pgsql://0.0.0.0:5432"
    storage: "inmemory:///dev-test/pgsql"
  - name: redis service
    mode: proxy
    source: "redis://0.0.0.0:16379"
    backend: "redis://0.0.0.0:6379"
    storage: "inmemory:///dev-test/redis"
health:
  path: "/health"
directory:
  path: "/directory"

