port: 9000
name: traffic-proxy dev-mode
servers:
  - name: backend service1
    mode: proxy
    source: "http://0.0.0.0:13000"
    backend: "http://0.0.0.0:3000"
    storage: "inmemory:///dev-test/service1"
  - name: backend service2
    mode: proxy
    source: "http://0.0.0.0:13001"
    backend: "http://0.0.0.0:3001"
    storage: "inmemory:///dev-test/service2"
  - name: mysql service
    mode: proxy
    source: "mysql://0.0.0.0:13306"
    backend: "mysql://0.0.0.0:3306"
    storage: "inmemory:///dev-test/mysql"
  - name: redis service
    mode: proxy
    source: "redis://0.0.0.0:15379"
    backend: "redis://0.0.0.0:5379"
    storage: "inmemory:///dev-test/redis"
health:
  path: "/health"
directory:
  path: "/directory"

